---
title: "ESM 244 Lab 1"
author: "Kira Archipov"
date: "2023-01-13"
output: html_document
---

```{r setup, include=TRUE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(sf)
#stands for simple features
library(tmap)
#good for visualizing map data

```

Workflow best practices: 
commit pull push

In terminal: 
ls - tells you all the folders within current repository 
ls -a - includes .git folder within project 

Environment over on top right - tells you which variables are in R memory 
read_csv is improved version of read.csv within tidyverse, faster and does a couple more things than read.csv

### Read in the data 
```{r}
sf_trees <- read_csv(here('data', 'sf_trees', 'sf_trees.csv'))

top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n = 5) %>% #find values that are max and just keep n amount 
  arrange(-tree_count)

ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count),
                                y = tree_count)) +
  geom_col() + 
  labs(y = 'Tree Count', x = 'Legal Status') + coord_flip() + theme_minimal()
```








